openapi: 3.0.3
info:
  title: Long Dictionary Service 1.0
  description: |-
    Specification for Long Dictionary Service Api
  contact:
    email: lplong31@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://longdict.com/api/v1
tags:
  - name: vocabulary
    description: Access to the vocabulary resources
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /vocabulary/{writting}:
    get:
      tags:
        - vocabulary
      summary: Find vocabulary by writting
      description: Returns a vocabulary
      operationId: getVocabulary
      parameters:
        - name: writting
          in: path
          description: Writing of vocabulary
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vocabulary'          
        '400':
          description: Invalid ID supplied
        '404':
          description: Vocabulary not found
components:
  schemas:
    Vocabulary:
      type: object
      properties:
        writting:
          type: string
          example: long
        meanings:
          type: array
          items:
            type: string
            example: continuing for a large amount of time
        examples:
          type: array
          items:
            type: string
            example: a long film/meeting
        vocabularyClass:
          type: string
          enum:
            - NOUN
            - PRONOUN
            - ADJECTIVE
            - ADVERB
            - VERB
            - DETERMINER
            - PREPOSITION
            - CONJUNCTION
            - INTERJECTION
            - IDIOM
        pronunciations:
          type: array
          items:
            $ref: '#/components/schemas/Pronunciation'
        extraVocabulary:
          type: array
          items:
            $ref: '#/components/schemas/ExtraVocabulary'
        # dictionary:
        #   $ref: '#/components/schemas/Dictionary'
    Pronunciation:
      type: object
      properties:
        ipa:
          type: string
          example: /lɑːŋ/
        voices:
          type: array
          items:
            $ref: '#/components/schemas/Voice'
    Voice:
      type: object
      properties:
        accent:
          type: string
          enum:
            - US
            - UK
        url:
          type: string
    ExtraVocabulary:
      type: object
      properties:
        writting:
          type: string
        relation:
          type: string
          enum:
            - SYNOMYM
            - ANTOMYM
            - RELATED
        url:
          type: string
    # Dictionary:
    #  type: string
    #  enum:
    #    - CAMBRIDGE
    #    - OXFORD